---
title: Create Single Plan
pagination_prev: null
hide_title: true
---

## Create Single Plan

Create a subscription plan with Spotflow.

<span style={{color: "orange"}}>`POST`</span> https://api.spotflow.co/api/v1/plans


## Headers



| <p style={{fontWeight: '400'}}>authorization <br></br> <span style={{color: "red"}}>`String`</span></p> | <p style={{fontWeight: '400'}}><span style={{color: "red"}}>`Bearer SECRET_KEY`</span> <br></br> *Include your secret key in the request header as a Bearer token for authorization. Unauthorized requests will result in a 401 HTTP status code*.</p> |
|:----------|:-----------|
| content-type <br></br> <span style={{color: "red"}}>`String`</span> | <span style={{color: "red"}}>`application/json`</span> |


## Body Parameters

| <p style={{fontWeight: '400'}}>title <br></br> <span style={{color: "red"}}>`String`</span></p> | <p style={{fontWeight: '400'}}>Name/Title of plan</p> |
|:---------|:---------|
| amount <br></br> <span style={{color: "red"}}>`Integer`</span> | Amount should be in the subunit of our supported currency i.e your local currency or USD. |
| frequency <br></br> <span style={{color: "red"}}>`String`</span> |  This simply means how often. Valid frequencies are: <span style={{color: "red"}}>`daily`</span>, <span style={{color: "red"}}>`weekly`</span>, <span style={{color: "red"}}>`monthly`</span>, <span style={{color: "red"}}>`quarterly`</span>, <span style={{color: "red"}}>`biannually`</span> (every 6 months), <span style={{color: "red"}}>`annually`</span>.|
| internalReference <br></br> <span style={{color: "red"}}>`String`</span> | A unique reference number generated by your company to identify each customer.|
| pricingOptions <br></br> <span style={{color: "red"}}>`String`</span> | Specify one or more amount or currency for your payment plan.|
| currency <br></br> <span style={{color: "red"}}>`String`</span> | Select the currency for the charges. Can either be in USD or in the local currency of your collection region.|

## Sample Request Body for Local Payments

```yaml
{
    "title": "My Nutrifit",
    "frequency": "DAILY",
    "internalReference": "ref-prod",
    "pricingOptions": [
    {
      "amount": 100,
      "currency": "NGN"
    },
    {
      "amount": 10,
      "currency": "GHS"
    }
  ]
}
```

## Sample Response for Local Payments

<span style={{color: "green"}}>`200 OK`</span>

<br></br>
<br></br>

```yaml
{
    "id": "acbabde0-1293-4b8b-9eb9-7e532e34d9bf",
    "title": "My Nutrifit",
    "frequency": "DAILY",
    "internalReference": "ref-prod",
    "status": "active",
    "regions": [
        "Ghana",
        "Nigeria"
    ],
    "subscribers": 0,
    "subscriptions": 0,
    "pricingOptions": [
        {
            "amount": 100,
            "currency": "NGN"
        },
        {
            "amount": 10,
            "currency": "GHS"
        }
    ]
}
```

## Sample Request Body for Global Payments

```yaml
{
    "title": "Global FitPlan",
    "frequency": "DAILY",
    "internalReference": "ref-usdplan",
    "pricingOptions": [
    {
      "amount": 0.5,
      "currency": "USD"
    }
  ]
}
```

## Sample Response for Global Payments

<span style={{color: "green"}}>`200 OK`</span>

<br></br>
<br></br>

```yaml
{
    "id": "250657ea-acda-491e-9e98-7889c30095af",
    "title": "Global FitPlan",
    "frequency": "DAILY",
    "internalReference": "ref-usdplan",
    "status": "active",
    "regions": [
        "Global"
    ],
    "subscribers": 0,
    "subscriptions": 0,
    "pricingOptions": [
        {
            "amount": 0.5,
            "currency": "USD"
        }
    ]
}
```